[package]
name = "wikigraph"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5", features = ["json"] }
serde  = { version = "1.0", features = ["derive"] }

glob   = "0.3"
pandoc = "0.8"
scraper = "0.18"

rayon   = "1.8"
anyhow  = "1.0"
